### ISSUE TITLE
Is there a way to plan only the link if when I have enough keys ?

### ISSUE THREAD

**Issue by CloudnuY** [mricon/ingress-fieldplan#12]

**Comment by danwie** [comment]
From the docs:

    idkfa: you have all the keys and hack/cooldown times should not be counted

**Comment by CloudnuY** [comment]
@danwie Thank you

My fault, I didn't look at the document carefully

**Comment by mricon** [comment]
I think you were asking something else. Do you mean, is there an option to only plan a link if you already have enough keys? I haven't done something like this for several reasons:

1. it's annoying to track how many keys you have and to put them into the spreadsheet
2. we can't optimize links and fields if we must carefully consider the number of keys
3. you're going to get at least 1-2 keys during the field op anyway
4. if you're stuck waiting for the portal cooldown, open another Niantic app and catch some pokemons or cast some spells. :)

-K
