### ISSUE TITLE
Attribute: 'NoneType' object has no attribute "Copy"

### ISSUE THREAD

**Issue by Bassel-T** [mricon/ingress-fieldplan#14]
I'm getting an error and can't figure out what the issue is.

`Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\sool1\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\sool1\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\sool1\Downloads\ingress-fieldplan-master\ingress-fieldplan-master\fieldplan.py", line 49, in queue_job
    b = mygraph.copy()
Traceback (most recent call last):
  File "C:\Users\sool1\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
AttributeError: 'NoneType' object has no attribute 'copy'`

**Comment by DeKaN** [comment]
> while every Windows process must spin up independently of the parent process that created it, Linux supports the fork(2) system call that creates a child processes already in possession of exactly the same resources as its parent: every data structure, open file, and database connection that existed in the parent process is still sitting there, open and ready to use, in the child.

It's the main reason

**Comment by mricon** [comment]
I'll have to look on how to port this to Windows. Sorry, I have no experience with that platform and the differences it has for python's multiprocessing.

**Comment by DeKaN** [comment]
@mricon I can push my dirty hack with copying fields

**Comment by mricon** [comment]
@DeKaN thanks for this -- I'll see if I can rebase it on the latest version and grok what's going on.

**Comment by DeKaN** [comment]
@mricon I've merged your changes into fix

**Comment by mricon** [comment]
@DeKaN merged, thanks!
