### ISSUE TITLE
Question: scenario - all portals are already captured

### ISSUE THREAD

**Issue by danwie** [mricon/ingress-fieldplan#19]
In my scenario all portals are usually my color already - and I have keys for them. Is there an even more optimal route in this scenario? Just curious. Maby there could be a optional column to specify the current colour of each portal?

**Comment by mricon** [comment]
Running with `--cooling idkfa` should get you almost exactly what you are looking for.

**Comment by danwie** [comment]
Thanks, that's what I'm currently using. However, what I'm wondering is if there is a more optimal route if all portals are already captured.
