### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'node'

### ISSUE THREAD

**Issue by sky80830** [mricon/ingress-fieldplan#24]
DiGraph update. node is replaced by nodes.
Changes required in maxfield.py and Triangle.py and gsheets.py
[changes.zip](https://github.com/mricon/ingress-fieldplan/files/3908739/changes.zip)

**Comment by sseagle** [comment]
Thanks for this, if you do the step by step pngs you also need to update animate.py, which I have managed to do and place here :)
[animate.py.zip](https://github.com/mricon/ingress-fieldplan/files/4464483/animate.py.zip)

**Comment by Joerchi** [comment]
Thanks @sseagle , thanks @sky80830 , for these two ZIP files. After having overwritten the original files with your patches, everything is working smoothly!

**Comment by mricon** [comment]
This should be fixed in the latest commit. Thanks for your help.
