### ISSUE TITLE
Maxfield v4.0

### ISSUE THREAD

**Issue by tvwenger** [mricon/ingress-fieldplan#25]
I've just updated Maxfield to version 4.0, which is a nearly complete re-write of the original code. It's way more efficient and optimized now, and the code is cleaner.

If you're interested in updating this, it would solve some of the other issues (DiGraph one, specifically). Alternatively, if you want to implement your google drive stuff in the v4.0 framework, I'd accept the pull request and add the feature to the website!

**Comment by mricon** [comment]
Congratulations on finishing the grad school. :) I'm taking a hiatus from Ingress during the winter months, but I'll definitely take a closer look at what's in v4.0 once it gets closer to spring and the outside air stops hurting my face.

**Comment by tvwenger** [comment]
Sounds good! Enjoy hibernation!
