### ISSUE TITLE
Formula parse error in Google Spreadsheet

### ISSUE THREAD

**Issue by danwie** [mricon/ingress-fieldplan#5]
There is a locale issue with Google Spreadsheet. Some locales use a comma as argument separators, others (e.g. some European countries) use semi-colons (;). Ingress Fieldplan use comma and because of this the HYPERLINK function does not work in my country.

Google Spreadsheet say "Formula parse error".

In other words HYPERLINK("http....","2 km") needs to be changed to HYPERLINK("http....";"2 km").

Could the separator be a option?

**Comment by mricon** [comment]
I'm hoping that 49879ff fixes this problem for you -- for now, I'm forcing the locale to en_US, as there are more corner cases than just semicolons for various other locales.

**Comment by danwie** [comment]
Thanks. Unfortunately it didn't help (I'm using the Google Spreadsheet app) - I still get a error message. Maby it is possible for me to change the locale? Anyway, it's not a biggie for me. So far I've been using this tool on places that I know all the locations of the portals already.

**Comment by mricon** [comment]
I think I'm fixing the wrong end. Try running "export LC_ALL=C" in the terminal before you run fieldplan.py.

**Comment by danwie** [comment]
I'm sorry - but that didn't make any difference.

**Comment by mricon** [comment]
Google now accepts semicolons in all locales, so a3c3af0 should fix this for you, finally.
