### ISSUE TITLE
Plan doesn't say I should get keys for portal before linking to it

### ISSUE THREAD

**Issue by danwie** [mricon/ingress-fieldplan#6]
I just noticed that the generated plan say several times that I should link to portal "Ancient viking stone" - but it doesn't mention that I should go to to this portal and get keys. Maby a bug?

[This is the plan (made by 25000 iterations)](https://docs.google.com/spreadsheets/d/1biddShVItG0Ud8AdpHYRISu_DEBhna1Th-cuD3b6aVY/edit?usp=sharing)

**Comment by mricon** [comment]
I've never had this happen, but I think I know how it would. The latest git tree should hopefully fix this for you and others.
